Update firebase-hosting-merge.yml

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -28,7 +28,11 @@ jobs:
           SECRET_NAME="FIREBASE_SERVICE_ACCOUNT_WRODLE_CLONEV2_3412_$ENVIRONMENT"
           echo "Secret name: $SECRET_NAME"  # Para depurar, puedes eliminarlo después
 
-          echo "FIREBASE_SERVICE_ACCOUNT=$SECRET_NAME" >> $GITHUB_ENV
+            if [ -z "${{ secrets[SECRET_NAME] }}" ]; then
+              echo "Error: The secret for environment $ENVIRONMENT was not found."
+              exit 1
+            fi
+           echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets[SECRET_NAME] }}" >> $GITHUB_ENV
 
       - name: Cache Node modules
         uses: actions/cache@v3
@@ -45,7 +49,7 @@ jobs:
         uses: FirebaseExtended/action-hosting-deploy@v0
         with:
           repoToken: ${{ secrets.GITHUB_TOKEN }}
-          firebaseServiceAccount: ${{ secrets["FIREBASE_SERVICE_ACCOUNT_WRODLE_CLONEV2_3412_${{ env.ENVIRONMENT }}"] }}
+          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
           channelId: live
           projectId: ${{ env.ENVIRONMENT == 'PRODUCTION' && 'wrodle-clonev2-3412' || 'wordle-clonev2-dev' }}
         
