Update firebase-hosting-merge.yml

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -10,6 +10,24 @@ jobs:
   build_and_deploy:
     runs-on: ubuntu-latest
     steps:
+      - name: Check out the code
+        uses: actions/checkout@v4
+
+      - name: Set environment variables
+        run: |
+          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
+            echo "ENVIRONMENT=production" >> $GITHUB_ENV
+          else 
+            echo "ENVIRONMENT=development" >> $GITHUB_ENV
+          fi
+
+      - name: Verify environment
+        run: |
+          echo "Using environment: $ENVIRONMENT"
+          if [ -z "${{ secrets['FIREBASE_SERVICE_ACCOUNT_WRODLE_CLONEV2_3412_' + github.event_name | toUpper }}]" ]; then
+            echo "Error: The secret for environment $ENVIRONMENT was not found."
+            exit 1
+          fi
 
       - name: Cache Node modules
         uses: actions/cache@v3
@@ -17,32 +35,15 @@ jobs:
           path: ~/.npm
           key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
           restore-keys: |
-              ${{ runnner.os }}-node-
-              
-      - uses: actions/checkout@v4
+            ${{ runner.os }}-node-
+
       - name: Install dependencies and build
         run: npm ci && npm run build
 
-      - name: Set enviroment variables
-        run: |
-          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
-            echo "ENVIRONMENT=production" >> $GITHUB_ENV
-          else 
-            echo "ENVIRONMENT=development" >> $GITHUB_ENV
-
-      - name: Verify environment
-        run: |
-          echo "Using environment: $ENVIRONMENT"
-          if [ -z "${{ secrets['FIREBASE_SERVICE_ACCOUNT_WRODLE_CLONEV2_3412_' + env.ENVIRONMENT | upper] }}" ]; then
-            echo "Error: The secret for environment $ENVIRONMENT was not found."
-            exit 1
-          fi
-         
       - uses: FirebaseExtended/action-hosting-deploy@v0
         with:
           repoToken: ${{ secrets.GITHUB_TOKEN }}
           firebaseServiceAccount: ${{ secrets['FIREBASE_SERVICE_ACCOUNT_WRODLE_CLONEV2_3412_' + env.ENVIRONMENT | upper] }}
           channelId: live
           projectId: ${{ env.ENVIRONMENT == 'production' && 'wrodle-clonev2-3412' || 'wordle-clonev2-dev'}}
-        
       
